;;; Automatically generated by ‘recentf’ on Thu Nov 17 12:11:37 2022.

(setq recentf-list
      '(
        "/Users/jose.edil/.emacs.d/config/emacs-config.org"
        "/Users/jose.edil/0-research/papers/2023-fdl-fact/paper/include/integrator.tex"
        "/Users/jose.edil/test2.txt"
        "/Users/jose.edil/2-development/haskell/rivika/src/Solver.hs"
        "/Users/jose.edil/2-development/haskell/rivika/src/Integrator.hs"
        "/Users/jose.edil/2-development/haskell/rivika/src/Examples/ImprovedLorenz.hs"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
